
DEFINE_ERROR(INAPPROPRIATE_INPUT_FILE_NAME_ERROR, 0x10, "Inappropriate name of input file")
DEFINE_ERROR(INAPPROPRIATE_OUTPUT_FILE_NAME_ERROR, 0x11, "Inappropriate name of output file")
DEFINE_ERROR(CANNOT_OPEN_INPUT_FILE_ERROR, 0x12, "Cannot open input file")
DEFINE_ERROR(CANNOT_OPEN_OUTPUT_FILE_ERROR, 0x13, "Cannot open output file")
DEFINE_ERROR(MEMORY_ALLOCATION_ERROR, 0x14, "Cannot allocate memory")
DEFINE_ERROR(BAD_JPL_FILE_ERROR, 0x15, "Bad jpl file")
DEFINE_ERROR(UNKNOWN_COMMAND_ERROR, 0x16, "Unknown command")
