

DEFINE_ERROR(INAPPROPRIATE_INPUT_FILE_NAME_ERROR, 0x10, "Inappropriate name of input file")
DEFINE_ERROR(INAPPROPRIATE_OUTPUT_FILE_NAME_ERROR, 0x11, "Inappropriate name of output file")
DEFINE_ERROR(CANNOT_OPEN_INPUT_FILE_ERROR, 0x12, "Cannot find input file")
DEFINE_ERROR(CANNOT_OPEN_OUTPUT_FILE_ERROR, 0x13, "Cannot open output file")
DEFINE_ERROR(MEMORY_ALLOCATION_ERROR, 0x14, "Cannot allocate memory")
DEFINE_ERROR(PUSHN_ERROR, 0x15, "Wrong pushn command")
DEFINE_ERROR(UNKNOWN_REGISTER, 0x16, "Unknown register")
DEFINE_ERROR(PUSHR_ERROR, 0x17, "Wrong pushr command")
DEFINE_ERROR(POP_ERROR, 0x18, "Wrong pop command")
DEFINE_ERROR(MOVR_ERROR, 0x19, "Wrong movr command")
DEFINE_ERROR(MOVN_ERROR, 0x1a, "Wrong movn command")
DEFINE_ERROR(MOVB_ERROR, 0x1b, "Wrong movb command")
DEFINE_ERROR(MOVW_ERROR, 0x1c, "Wrong movw command")
DEFINE_ERROR(MOVD_ERROR, 0x1d, "Wrong movd command")
DEFINE_ERROR(MOVQ_ERROR, 0x1e, "Wrong movq command")
DEFINE_ERROR(WRTB_ERROR, 0x1f, "Wrong wrtb command")
DEFINE_ERROR(WRTW_ERROR, 0x20, "Wrong wrtw command")
DEFINE_ERROR(WRTD_ERROR, 0x21, "Wrong wrtd command")
DEFINE_ERROR(WRTQ_ERROR, 0x22, "Wrong wrtq command")
DEFINE_ERROR(MULTIPLE_LABEL_ERROR, 0x23, "There was a previous declaration of label")
DEFINE_ERROR(OFFSET_ERROR, 0x24, "Wrong offset command")
DEFINE_ERROR(CALL_ERROR, 0x25, "Wrong call command")
DEFINE_ERROR(JMP_ERROR, 0x26, "Wrong jmp command")
DEFINE_ERROR(JE_ERROR, 0x27, "Wrong je command")
DEFINE_ERROR(JNE_ERROR, 0x28, "Wrong jne command")
DEFINE_ERROR(JA_ERROR, 0x29, "Wrong ja command")
DEFINE_ERROR(JAE_ERROR, 0x2a, "Wrong jae command")
DEFINE_ERROR(JB_ERROR, 0x2b, "Wrong jb command")
DEFINE_ERROR(JBE_ERROR, 0x2c, "Wrong jbe command")
DEFINE_ERROR(DB_ERROR, 0x2d, "Wrong db command")
DEFINE_ERROR(DW_ERROR, 0x2e, "Wrong dw command")
DEFINE_ERROR(DD_ERROR, 0x2f, "Wrong dd command")
DEFINE_ERROR(DQ_ERROR, 0x30, "Wrong dq command")
DEFINE_ERROR(LABEL_NOT_FOUND_ERROR, 0x31, "Label has not been found")
DEFINE_ERROR(UNKNOWN_COMMAND_ERROR, 0x32, "Unknown command")